---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/e211_website.yml
  tasks:
    - name: fill and copy templates for website
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ website_template_list }}"
    - name: make the html source folder
      file:
        path: "{{ dest_dir }}"
        state: directory
    - name: rsync the rendered book
      ansible.posix.synchronize:
        src: "{{ book_local_html }}"
        dest: "{{ dest_dir }}"
        group: "no"






